// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmuqtjrepvuadrijjhxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtdXF0anJlcHZ1YWRyaWpqaHh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2Mzg0NTksImV4cCI6MjA2OTIxNDQ1OX0.BCi5mq7OGNAsuFqqp0vlD8hVgFKDX9CWl3Ptn-9HkGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});